server:
  port: 9001
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: MysqlDB
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

logging:
  level:
    com:
      liuzibin:
        dao: debug